version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    command: npm run start
    # ports:
    #   - "3000:3000"
    environment:
      NODE_ENV: development
      # DEBUG: nodejs-docker-express:*